### ISSUE TITLE
Socket disconnected, but session could not be loaded to pass to configured disconnect handler

### ISSUE THREAD

**Issue by netlander** [Karnith/sails-generate-new-gulp#13]
Getting this error on a gulp generated sails project:

```
warn: Socket disconnected, but session could not be loaded to pass to configured disconnect handler: `sails.config.sockets.afterDisconnect()`.  Will pass a fake, empty session as argument to lifecycle callback.  Details:
 Error: Session could not be loaded
    at _createError (C:\Users\maste_000\AppData\Roaming\npm\node_modules\sails\lib\hooks\session\index.js:271:21)
    at Immediate.<anonymous> (C:\Users\maste_000\AppData\Roaming\npm\node_modules\sails\lib\hooks\session\index.js:274:13)
    at Immediate.immediate._onImmediate (timers.js:425:18)
    at processImmediate [as _immediateCallback] (timers.js:368:17) { [Error: Session could not be loaded] code: 'E_SESSION' }
```

Is there something fundamentally wrong with the codebase at this point?

**Comment by Karnith** [comment]
sails-generate new-gulp is no longer active. Use [machinepack-sailsgulpify](https://github.com/Karnith/machinepack-sailsgulpify) instead please.

**Comment by naingmahar** [comment]
same for me. Any solution for this?
