### ISSUE TITLE
"TypeError: callback is not a function" when trying to create a new sails app

### ISSUE THREAD

**Issue by Xayer** [Karnith/sails-generate-new-gulp#14]
Hello.

I'm trying to create a new sails app using this gulp function.

When I run `sails new anotherTestProject` I get the following error:

```
/usr/local/lib/node_modules/sails-generate-new-gulp/node_modules/async/dist/async.js:3679
            callback(err, results);
            ^

TypeError: callback is not a function
    at /usr/local/lib/node_modules/sails-generate-new-gulp/node_modules/async/dist/async.js:3679:13
    at /usr/local/lib/node_modules/sails-generate-new-gulp/node_modules/async/dist/async.js:952:25
    at iteratorCallback (/usr/local/lib/node_modules/sails-generate-new-gulp/node_modules/async/dist/async.js:997:17)
    at /usr/local/lib/node_modules/sails-generate-new-gulp/node_modules/async/dist/async.js:847:20
    at /usr/local/lib/node_modules/sails-generate-new-gulp/node_modules/async/dist/async.js:3676:17
    at /usr/local/lib/node_modules/sails-generate-new-gulp/node_modules/async/dist/async.js:339:31
    at /usr/local/lib/node_modules/sails-generate-new-gulp/lib/after.js:78:5
    at FSReqWrap.oncomplete (fs.js:82:15)
```

I tried rerunning it a few times without luck unfortunately.

**Comment by mrfrac** [comment]
+1
